Códigos balta.io/1961 - Segurança no ASP.NET Core/1961-master/basic/Models/TodoList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TodoCore.Models
{
    public class TodoList
    {
        public TodoList()
        {
            Todos = new List<TodoItem>();
            Id = Guid.NewGuid();
        }

        [Key]
        public Guid Id { get; set; }

        [Display(Name = "Nome da Lista")]
        [StringLength(40, ErrorMessage = "Este campo deve conter apenas 40 caracteres")]
        [Required(ErrorMessage = "Campo Obrigatório")]
        public string Title { get; set; }
        public ICollection<TodoItem> Todos { get; set; }
    }
}

Códigos balta.io/1961 - Segurança no ASP.NET Core/1961-master/basic/Controllers/TodoController.cs
using TodoCore.Data;
using TodoCore.Models;
using Microsoft.AspNet.Mvc;
using System.Threading.Tasks;
using Microsoft.Data.Entity;
using System.Linq;
using System;

namespace TodoCore.Controllers
{
    public class TodoController : Controller
    {
        private AppDataContext _db;

        public TodoController(AppDataContext context)
        {
            _db = context;
        }

        public async Task<IActionResult> Index(Guid id)
        {
            ViewBag.Id = id;
            return View(await _db.TodoItems.Where(x => x.TodoListId == id).OrderBy(x => x.Done).ToListAsync());
        }

        public IActionResult Create(Guid id)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TodoItem todoItem)
        {
            if (ModelState.IsValid)
            {
                todoItem.Id = Guid.NewGuid();
                _db.TodoItems.Add(todoItem);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index", new { id = todoItem.TodoListId });
            }

            return View(todoItem);
        }

        public async Task<IActionResult> MarkAsDone(Guid id)
        {
            var todo = await _db.TodoItems.SingleAsync(m => m.Id == id);
            if (todo == null)
                return HttpNotFound();

            todo.Done = true;
            _db.Update(todo);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index", new { Id = todo.TodoListId });
        }
        
        public async Task<IActionResult> Delete(Guid id)
        {
            var todo = await _db.TodoItems.SingleAsync(m => m.Id == id);
            if (todo == null)
                return HttpNotFound();

            _db.TodoItems.Remove(todo);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index", new { Id = todo.TodoListId });
        }
    }
}

Códigos balta.io/1961 - Segurança no ASP.NET Core/1961-master/basic/Controllers/TodoListController.cs
using TodoCore.Data;
using TodoCore.Models;
using Microsoft.AspNet.Mvc;
using System.Threading.Tasks;
using Microsoft.Data.Entity;
using System;

namespace TodoCore.Controllers
{
    public class TodoListController : Controller
    {
        private AppDataContext _db;

        public TodoListController(AppDataContext context)
        {
            _db = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _db.TodoLists.Include(x => x.Todos).ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TodoList todoList)
        {
            if (ModelState.IsValid)
            {
                _db.TodoLists.Add(todoList);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(todoList);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
                return HttpNotFound();

            TodoList todoList = await _db.TodoLists.SingleAsync(m => m.Id == id);
            if (todoList == null)
                return HttpNotFound();

            return View(todoList);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == null)
                return HttpNotFound();

            TodoList todoList = await _db.TodoLists.SingleAsync(m => m.Id == id);
            if (todoList == null)
                return HttpNotFound();

            return View(todoList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TodoList todoList)
        {
            if (ModelState.IsValid)
            {
                _db.Update(todoList);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(todoList);
        }

        [ActionName("Delete")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == null)
                return HttpNotFound();

            TodoList todoList = await _db.TodoLists.SingleAsync(m => m.Id == id);
            if (todoList == null)
                return HttpNotFound();

            return View(todoList);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            TodoList todoList = await _db.TodoLists.SingleAsync(m => m.Id == id);
            _db.TodoLists.Remove(todoList);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Códigos balta.io/1961 - Segurança no ASP.NET Core/1961-master/basic/Views/TodoList/Create.cshtml
@model TodoCore.Models.TodoList

@{
    ViewData["Title"] = "Nova Lista";
}


<form asp-action="Create">
    <div class="form-horizontal">
        <h4>@ViewData["Title"]</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Voltar para a lista</a>
</div>

Códigos balta.io/1961 - Segurança no ASP.NET Core/1961-master/basic/Views/TodoList/Delete.cshtml
@model TodoCore.Models.TodoList

@{
    ViewData["Title"] = "Excluir Lista de Tarefas";
}

<h2>@ViewData["Title"]</h2>

<h3>Tem certeza que deseja excluir este registro?</h3>
<div>
    <h4>Lista de Tarefas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            <a asp-action="Index">Cancelar</a>
        </div>
    </form>
</div>

Códigos balta.io/1961 - Segurança no ASP.NET Core/1961-master/basic/Views/TodoList/Details.cshtml
@model TodoCore.Models.TodoList

@{
    ViewData["Title"] = "Detalhes";
}

<h2>@ViewData["Title"]</h2>

<div>
    <h4>Lista de Tarefas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
</div>
<p>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Voltar para Lista</a>
</p>

Códigos balta.io/1961 - Segurança no ASP.NET Core/1961-master/basic/Views/TodoList/Edit.cshtml
@model TodoCore.Models.TodoList

@{
    ViewData["Title"] = "Edição";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Lista de Tarefas</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Voltar para Lista</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Códigos balta.io/1961 - Segurança no ASP.NET Core/1961-master/basic/Views/TodoList/Index.cshtml
@model IEnumerable<TodoCore.Models.TodoList>
@{
    ViewData["Title"] = "Listas de Tarefas";
}

@section topmenu{
    <ul class="nav navbar-nav navbar-right">
        <li><a asp-controller="TodoList" asp-action="Create"><i class="fa fa-plus"></i>&nbsp; NOVA LISTA</a></li>
    </ul>
}

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th class="text-center">Lista</th>
            <th class="text-center">Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model){
            <tr>
                <td class="text-center">@item.Title (@item.Todos.Count)</td>
                <td class="text-center">
                    <div class="btn-group">
                        <a class="btn btn-sm btn-default" asp-controller="TodoList" asp-action="Details" asp-route-id="@item.Id" title="Detalhes"><i class="fa fa-list-alt"></i></a>
                        <a class="btn btn-sm btn-info" asp-controller="TodoList" asp-action="Edit" asp-route-id="@item.Id" title="Editar"><i class="fa fa-edit"></i></a>
                        <a class="btn btn-sm btn-danger" asp-controller="TodoList" asp-action="Delete" asp-route-id="@item.Id" title="Excluir"><i class="fa fa-remove"></i></a>
                        <a class="btn btn-sm btn-success" asp-controller="Todo" asp-action="Index" asp-route-id="@item.Id" title="Itens"><i class="fa fa-bars"></i></a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>